# Generated by Django 4.0.2 on 2022-03-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digeek',
            fields=[
                ('digeekid', models.AutoField(primary_key=True, serialize=False)),
                ('edicion', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'digeek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('eventosid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('expositorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('autobiografia', models.TextField()),
                ('carrera', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'expositor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('imagenesid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('redes_socialesid', models.AutoField(primary_key=True, serialize=False)),
                ('red_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'redes_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('visitanteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('proviene_de', models.CharField(max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=7, null=True)),
                ('url_comprobante_pago', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'visitante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDigeek',
            fields=[
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='digeek.visitante')),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'registro_digeek',
                'managed': False,
            },
        ),
    ]
